### ISSUE TITLE
Не открывается сайт

### ISSUE THREAD

**Issue by KCH0000** [astra50/astra50.ru#10]
У некоторых не открывается сайт по ссылке astra50.ru, но не точно.

**Comment by grachevko** [comment]
И как это локализовать, если всё открывается?)

**Comment by KCH0000** [comment]
Не открывается на старых браузерах с ошибкой "не удалось установить защищенное соединение"

**Comment by grachevko** [comment]
Надо либо включить SSL шифрование, либо обновить браузер. Отключать защиту хреновая затея.
