### ISSUE TITLE
Страница оплаты взносов

### ISSUE THREAD

**Issue by KCH0000** [astra50/astra50.ru#7]
На страницы описание, какими способами можно производить оплату.
Текст: на странице

> Уважаемые жители СНТ "Астра" вас доступны несколько способов оплаты ежемесячных и целевых взносов". 
> Для оплаты вам нужно знать свои лицевые счета, которые состоят их 4х цифр и привязаны к номеру участка. 
> Для оплаты ежемесячных взносов нужно знать ваши номера лицевых счетов (1000+Номер Участка), для целевого взноса (2000+Номер Участка). В большинстве случаев при при правильном указании счета вам будет автоматически показана ваша задолженность для оплаты.
> Например.
> 1. Для участка №5 лицевые счета 1005 и 2005 соответственно.
> 2. Для участка №16 лицевые счета 1016 и 2016 соответственно.
> 3. Для участка №104 лицевые счета 1104 и 2104 соответственно. 
> Доступны следующие способы:

Доступны следующие способы оплаты
1. СберБанк Онлайн
2. Мобильном приложении СберБанка
3. Перевод на карту Tinkoff
4. Оплата по реквизитам СНТ «Астра»
5. Оплата в отделении СберБанка
6. Наличные средства.

**Comment by KCH0000** [comment]
Сбербанк Онлайн
лого [http://toplogos.ru/images/logo-sberbank-online.png](url)

**Comment by KCH0000** [comment]
Сбербанк Мобаил
лого https://s.gorodche.ru/localStorage/news/93/ec/9f/94/93ec9f94_resizedScaled_817to1226.png

**Comment by KCH0000** [comment]
Лого страницы и иконки для перехода https://static2.tinkoff.ru/portal/tinkoffbank-general-logo/tinkoff-bank-general-logo-1.png
Текст для страницы.

Оплата с помощью перевода на карту Tinkoff Bank.
**Внимание данный вид оплаты доступен только для клиентов Tinkoff Bank, если вы произведете оплату с карты другого банка, то мы не сможем идентифицировать ваш платеж.**
1. Откройте приложение "Тинькофф" для физических лиц, либо войдите на личный кабинет на сайте банка https://www.tinkoff.ru/login/ (открывается в отдельном окне).
2. Выберите карту для оплаты взносов и нажмите кнопку **"Оплатить"** 
![image](https://user-images.githubusercontent.com/28162151/32109817-74cb9bd2-bb3e-11e7-883f-9ea1c167df4c.png)
3. Выберите пункт оплатить **"Людям"**
![image](https://user-images.githubusercontent.com/28162151/32109849-8faf1276-bb3e-11e7-93eb-859bfcd472fb.png)
4. Выберите любой из пунктов **"Оплатить по QR коду"** либо **"По номеру договора"**, который считаете для себя удобным. 
![image](https://user-images.githubusercontent.com/28162151/32109935-d85170f0-bb3e-11e7-9d54-a0d0f358a5ed.png)
5. Сканируйте **QR код** на этой странице, либо укажите номер договора **5005388003**.
В поле **"Сообщение получателю"** укажите "Оплата ежемесячных взносов уч.ХХХ", либо "Оплата целевого взноса уч.ХХХ", где ХХХ - номер вашего участка. 
Сумму к оплате, вы можете узнать из последнего отчета в разделе "Финансовая отчетность" 
![image](https://user-images.githubusercontent.com/28162151/32110119-6cbd67bc-bb3f-11e7-9835-07594d663c85.png)
![image](https://user-images.githubusercontent.com/28162151/32110126-71cd7cf6-bb3f-11e7-8737-4b79e04193c8.png)

**Comment by KCH0000** [comment]
Оплата по реквизитам юридического лица.
лого страницы и иконки для перехода 
http://kinvestor.ru/wp-content/uploads/2016/08/bankovsky-perevod-broker.png
Текст страницы.
Оплата взнос банковским переводом на счет СНТ "Астра"

Реквизиты для платежного поручения:
Название: **СНТ "АСТРА"**
ОГРН: 1025007516820
ИНН: **5074022777**
КПП: **507401001**
Юридический Адрес: 142143,   МО, Подольский гор.округ, вблизи д. Борисовка

Расчетный счет: **40703810811010117536**
Банк: ФИЛИАЛ «БИЗНЕС» ПАО «СОВКОМБАНК» г.Москва
БИК: **044525058**
Кор. Счет: 30101810045250000058

**Назначение платежа**
"Оплата ежемесячных взносов по участку №ХХХ"
Либо
"Оплата целевых взносов по участку №ХХХ"
где ХХХ - номер вашего участка.

**Comment by KCH0000** [comment]
В отделении сбербанка
Лого страницы http://stroim-pro.ru/images/logo-blue.png
Оплата по квитанции в отделениях СберБанка.

**Квитанцию вы можете получить в доме сторожа, либо заказать электронную копию по электронной почте.** 
Для получения электронной квитанции, вам нужно в форме обратной связи в разделе "Предложения" оформить заявку на получение квитанции https://astra50.ru/suggestions. 

**В заявке необходимо указать:**
1. Желаемую сумму к оплате, 
2. Назначение "членские взносы", или "целевые взносы", или заказать сразу две квитанции.
3. Указать номера участков для которых нужны квитанции.

**Comment by KCH0000** [comment]
Наличные средства.
лого https://razvitoys.ru/image/catalog/icon/ikonka-oplata-nalichnymi.png
Текст страницы.
**Оплата наличными в доме кассира.**
## Внимание, прием наличных временно приостановлен и осуществляется только при согласовании с Председателем. Используйте другие способы оплаты.

**Comment by grachevko** [comment]
Каждый способ оплаты отображается на своей отдельной странице?
На основной странице краткое описание и иконки для перехода?
Если да, иконки расположить без текста просто внизу страницы в ряд?

**Comment by KCH0000** [comment]
Для каждой инструкции своя страница, на главной станице иконки с кратким описанием, как в первом сообщении. Инконки расоплогаются так, чтобы слепошарые их нажали.
